"""firts commit with all migrations (patient and dentist whitout relationships)

Revision ID: 855da157f258
Revises: 
Create Date: 2024-10-27 02:00:55.143674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "855da157f258"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dentists",
        sa.Column("id_dentist", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("licence", sa.VARCHAR(length=100), nullable=True),
        sa.Column("id_state", sa.Integer(), nullable=True),
        sa.Column("inactive_days", sa.Integer(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("id_schedule", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_dentist"),
        sa.UniqueConstraint("licence"),
    )
    op.create_table(
        "patients",
        sa.Column("id_patient", sa.Integer(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("last_name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("address", sa.VARCHAR(length=200), nullable=True),
        sa.Column("departure_date", sa.VARCHAR(length=20), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("dni", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_patient"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("patients")
    op.drop_table("dentists")
    # ### end Alembic commands ###
